apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zb9py6ihj-nodejs 
  janus-idp.io/tekton: zb9py6ihj-nodejs
  backstage.io/kubernetes-id: zb9py6ihj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zb9py6ihj-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml